app = 'bt-servant-web-client'
primary_region = 'iad'

[build]

[env]
  AUTH_TRUST_HOST = "true"

[http_service]
  internal_port = 3000
  force_https = true
  idle_timeout = 180
  headers_read_timeout = 180
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[checks]
  [checks.health]
    grace_period = "30s"
    interval = "30s"
    method = "GET"
    path = "/login"
    port = 3000
    timeout = "5s"
    type = "http"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
